In [11]:
import numpy as np

N = 8
x = np.arange(0, N)
y = np.array(list(reversed(x)))
matrix = np.diag(y, k=0)
z = np.full(N, 1)
print(matrix)
print(sum(np.dot(matrix, z)))

[[7 0 0 0 0 0 0 0]
 [0 6 0 0 0 0 0 0]
 [0 0 5 0 0 0 0 0]
 [0 0 0 4 0 0 0 0]
 [0 0 0 0 3 0 0 0]
 [0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0]]
28
